BetterGlauco/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_view
from django.urls import include, path

from .views import Contato, Homepage, Sobre

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Homepage.as_view(), name='homepage'),
    path('contato/', Contato.as_view(), name='contato'),
    path('invest/', include('investimento.urls', namespace='investimento')),
    path(
        'alocacao/',
        include('invest_alocacao.urls', namespace='invest_alocacao'),
    ),
    path(
        'operacao/',
        include('invest_operacao.urls', namespace='invest_operacao'),
    ),
    path(
        'atualizacao/',
        include('invest_atualizacao.urls', namespace='invest_atualizacao'),
    ),
    path(
        'login/',
        auth_view.LoginView.as_view(template_name='login.html'),
        name='login',
    ),
    path(
        'logout/',
        auth_view.LogoutView.as_view(template_name='logout.html'),
        name='logout',
    ),
    path('sobre/', Sobre.as_view(), name='sobre'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

invest_alocacao/urls.py
from django.urls import path

from .views import (
    ConfiguracaoMenu,
    ConfigurarAtivo,
    ConfigurarAtivoAlocacao,
    ConfigurarAtivoAlocacaoEditar,
    ConfigurarAtivoAlocacaoNovo,
    ConfigurarAtivoEditar,
    ConfigurarAtivoNovo,
    ConfigurarCaixa,
    ConfigurarCaixaEditar,
    ConfigurarCaixaNovo,
    ConfigurarInstituicaoFinanceira,
    ConfigurarInstituicaoFinanceiraEditar,
    ConfigurarInstituicaoFinanceiraNovo,
    ConfigurarSubCaixa,
    ConfigurarSubCaixaEditar,
    ConfigurarSubCaixaNovo,
    InicioAlocacao,
)

app_name = 'invest_alocacao'

urlpatterns = [
    path('', InicioAlocacao.as_view(), name='inicio_alocacao'),
    path('config/', ConfiguracaoMenu.as_view(), name='configuracao'),
    path('config/ativo/', ConfigurarAtivo.as_view(), name='config_ativos'),
    path(
        'config/ativo/novo/',
        ConfigurarAtivoNovo.as_view(),
        name='config_ativo_novo',
    ),
    path(
        'config/ativo/editar/<int:pk>',
        ConfigurarAtivoEditar.as_view(),
        name='config_ativo_editar',
    ),
    path(
        'config/ativo_alocacao/',
        ConfigurarAtivoAlocacao.as_view(),
        name='config_ativos_alocacao',
    ),
    path(
        'config/ativo_alocacao/novo/',
        ConfigurarAtivoAlocacaoNovo.as_view(),
        name='config_ativo_alocacao_novo',
    ),
    path(
        'config/ativo_alocacao/editar/<int:pk>',
        ConfigurarAtivoAlocacaoEditar.as_view(),
        name='config_ativo_alocacao_editar',
    ),
    path('config/caixa/', ConfigurarCaixa.as_view(), name='config_caixa'),
    path(
        'config/caixa/novo/',
        ConfigurarCaixaNovo.as_view(),
        name='config_caixa_novo',
    ),
    path(
        'config/caixa/editar/<int:pk>',
        ConfigurarCaixaEditar.as_view(),
        name='config_caixa_editar',
    ),
    path(
        'config/classe_ativo/',
        ConfigurarSubCaixa.as_view(),
        name='config_classe_ativo',
    ),
    path(
        'config/classe_ativo/novo/',
        ConfigurarSubCaixaNovo.as_view(),
        name='config_classe_ativo_novo',
    ),
    path(
        'config/classe_ativo/editar/<int:pk>',
        ConfigurarSubCaixaEditar.as_view(),
        name='config_classe_ativo_editar',
    ),
    path(
        'config/instituicao_financeira/',
        ConfigurarInstituicaoFinanceira.as_view(),
        name='config_instituicao_financeira',
    ),
    path(
        'config/instituicao_financeira/novo/',
        ConfigurarInstituicaoFinanceiraNovo.as_view(),
        name='config_instituicao_financeira_novo',
    ),
    path(
        'config/instituicao_financeira/editar/<int:pk>',
        ConfigurarInstituicaoFinanceiraEditar.as_view(),
        name='config_instituicao_financeira_editar',
    ),
]

investimento/urls.py
from django.urls import path

from .views import (
    Ajuda,
    HomeInvestimento,
    Imposto_bdr_usa,
    Valor_compra,
)

app_name = 'investimento'

urlpatterns = [
    path('', HomeInvestimento.as_view(), name='home_investimento'),
    path('help/', Ajuda.as_view(), name='ajuda_inicio'),
    path(
        'imposto-dividendo-bdr/',
        Imposto_bdr_usa.as_view(),
        name='imposto_dividendo_bdr',
    ),
    path('valor-compra/', Valor_compra.as_view(), name='valor_compra'),
]

investimento/forms.py
from typing import Any
from django import forms
from .models import Ativo, Caixa, InstituicaoFinanceira
from BetterGlauco.funcoes_auxiliares import Funcoes_auxiliares


class FormAtivo(forms.ModelForm):
    
    class Meta:
        model = Ativo
        fields = '__all__'
        widgets = {
            'desdobramento': forms.NumberInput(attrs={'step': 1}),
        }


class FormCaixa(forms.ModelForm):
    
    class Meta:
        model = Caixa
        fields = '__all__'
        exclude = ('perfil',)
        
        
class FormInstituicaoFinanceira(forms.ModelForm):
    
    class Meta:
        model = InstituicaoFinanceira
        fields = '__all__'
        exclude = ('perfil',)
        

investimento/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from BetterGlauco.funcoes_auxiliares import Funcoes_auxiliares
from BetterGlauco.parametro import Constante

from .bdr import BDR


class HomeInvestimento(LoginRequiredMixin, TemplateView):
    template_name = 'invest_inicio.html'

    def get_login_url(self) -> str:
        return super().get_login_url()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['id_perfil_selecionado'] = Funcoes_auxiliares.get_perfil_ativo(
            self.request, **kwargs
        )
        return context


class Ajuda(LoginRequiredMixin, TemplateView):
    template_name = 'ajuda_inicio.html'


class Imposto_bdr_usa(LoginRequiredMixin, TemplateView):
    template_name = 'bdr_imposto_usa.html'
    _CONSTANTE = Constante()
    tabela = {}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['id_perfil_selecionado'] = Funcoes_auxiliares.get_perfil_ativo(
            self.request, **kwargs
        )
        valor_dividendos = Funcoes_auxiliares.converte_numero_str(
            self.request.GET.get('valor_dividendos')
        )
        indice_imposto = self._CONSTANTE.BDR_IMPOSTO_DIVIDENDOS_USA()

        self.tabela['Dividendos recebidos (R$)'] = valor_dividendos
        imposto_retido = valor_dividendos * indice_imposto
        self.tabela['Imposto de Renda EUA retido na fonte estimado (R$)'] = (
            imposto_retido
        )

        context['tabela_resultados'] = self.tabela
        return context


class Valor_compra(LoginRequiredMixin, TemplateView):
    template_name = 'valor_compra.html'
    calculo_bdr = {'Compra': {}, 'Venda': {}}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['id_perfil_selecionado'] = Funcoes_auxiliares.get_perfil_ativo(
            self.request, **kwargs
        )
        bdr_ativo = BDR(self.request, self.request.GET.get('ticket'))
        if bdr_ativo.ativo_selecionado.ticket:
            self.monta_tabela_custos(bdr_ativo)
        context['calculo_bdr'] = self.calculo_bdr
        return context

    def monta_tabela_custos(self, bdr):
        valor_US_digitado = Funcoes_auxiliares.converte_numero_str(
            self.request.GET.get('valor_US')
        )
        bdr.calcular_preco_referencia(valor_US_digitado)
        self.gera_linha_tabela('Compra', bdr)
        self.gera_linha_tabela('Venda', bdr)

    def gera_linha_tabela(self, operacao, bdr):
        valor_BR_digitado = Funcoes_auxiliares.converte_numero_str(
            self.request.GET.get('valor_BDR')
        )

        self.calculo_bdr[operacao]['Ticket'] = bdr.ativo_selecionado.ticket
        self.calculo_bdr[operacao]['USA'] = (
            bdr.ativo_selecionado.ticket_original
        )
        self.calculo_bdr[operacao]['Desdobramento'] = int(
            bdr.ativo_selecionado.desdobramento
        )
        self.calculo_bdr[operacao]['Custo BDR'] = bdr.custos_bdr
        self.calculo_bdr[operacao]['Preço (U$)'] = bdr.ticket_original_valor_us

        if operacao == 'Venda':
            self.calculo_bdr[operacao]['Dólar (R$)'] = '{:.2f}'.format(
                bdr.dolar_compra
            )
            self.calculo_bdr[operacao]['Preço referência (R$)'] = (
                '{:.2f}'.format(bdr.preco_referencia_venda)
            )
        else:
            self.calculo_bdr[operacao]['Dólar (R$)'] = '{:.2f}'.format(
                bdr.dolar_venda
            )
            self.calculo_bdr[operacao]['Preço referência (R$)'] = (
                '{:.2f}'.format(bdr.preco_referencia_compra)
            )

        self.calculo_bdr[operacao]['Preço atual (R$)'] = '{:.2f}'.format(
            valor_BR_digitado
        )
        if bdr.preco_referencia_compra == 0:
            spread = 0
        else:
            spread = (valor_BR_digitado / bdr.preco_referencia_compra) - 1
        self.calculo_bdr[operacao]['Spread'] = '{:.2%}'.format(spread)

investimento/templates/ajuda_inicio.html
{% extends 'modelo_area-logada.html' %}


{% block titulo %}
    Better Glauco - Investimentos
{% endblock %}


{% block conteudo %}


<h1  class="font-semibold text-2xl mb-4">
    Help do sistema
</h1>


{% endblock %}

investimento/templates/bdr_imposto_usa.html
{% extends 'modelo_investimentos.html' %}

{% block titulo_pagina %}
BDR: Obter o valor do imposto de renda deduzido na fonte nos EUA
{% endblock %}


{% block conteudo_investimentos %}

<div class= "grid justify-center">
    <form method="get" action="{% url 'investimento:imposto_dividendo_bdr' %}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        <div class="form-group grid grid-cols-2 grid-rows-3 gap-x-4 gap-y-0"> 
            <label for="valor_dividendos" class="col-start-1 row-start-1 form-label text-gray-500">Valor Dividendos (R$)</label>
            <input type="text" name="valor_dividendos" 
                                value="{{request.GET.valor_dividendos}}"  
                                placeholder="ex: 0,0" 
                                class= "col-start-1 row-start-2 form-control
                                        rounded-md border-2 border-gray-100 border-solid 
                                        text-black" />          
            <button type="submit" class="col-start-2 row-start-2 form-check 
                                        bg-amber-900 w-full mx-4 rounded-md
                                        text-white text-lg" >
                Calcular
            </button>
            <div class="col-start-1 col-span-2 row-start-3 text-gray-500 text-xs" >
              <p> </p>
            </div>
        </div>
    </form>
</div>

<div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full">
          <thead class="bg-amber-900 border-b">
            <tr>
                  {% for chave in tabela_resultados %}
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
                          {{ chave }}
                    </th>
                  {% endfor %}
            </tr>
          </thead>
          <tbody>
            <tr class="bg-gray-100 border-b">
              {% for chave, valor in tabela_resultados.items %}
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                      {{ valor }}
                  </td>
              {% endfor %}
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>



{% endblock %}

investimento/templates/brd_imposto_usa.html
{% extends 'modelo_investimentos.html' %}

{% block titulo_pagina %}
BRD: Obter o valor do imposto de renda deduzido na fonte nos EUA
{% endblock %}


{% block conteudo_investimentos %}

<div class= "grid justify-center">
    <form method="get" action="{% url 'investimento:imposto_dividendo_brd' %}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        <div class="form-group grid grid-cols-2 grid-rows-3 gap-x-4 gap-y-0"> 
            <label for="valor_dividendos" class="col-start-1 row-start-1 form-label text-gray-500">Valor Dividendos (R$)</label>
            <input type="text" name="valor_dividendos" 
                                value="{{request.GET.valor_dividendos}}"  
                                placeholder="ex: 0,0" 
                                class= "col-start-1 row-start-2 form-control
                                        rounded-md border-2 border-gray-100 border-solid 
                                        text-black" />          
            <button type="submit" class="col-start-2 row-start-2 form-check 
                                        bg-amber-900 w-full mx-4 rounded-md
                                        text-white text-lg" >
                Calcular
            </button>
            <div class="col-start-1 col-span-2 row-start-3 text-gray-500 text-xs" >
              <p> </p>
            </div>
        </div>
    </form>
</div>

<div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full">
          <thead class="bg-amber-900 border-b">
            <tr>
                  {% for chave in tabela_resultados %}
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
                          {{ chave }}
                    </th>
                  {% endfor %}
            </tr>
          </thead>
          <tbody>
            <tr class="bg-gray-100 border-b">
              {% for chave, valor in tabela_resultados.items %}
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                      {{ valor }}
                  </td>
              {% endfor %}
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>



{% endblock %}

investimento/templates/config_ativos_editar.html
{% extends 'modelo_investimentos.html' %}
{% load crispy_forms_tags %}

{% block titulo_pagina %}
    {% if form.instance.pk %}
            Atualizar ativo
    {% else %}
            Cadastrar ativo
    {% endif %}
{% endblock %}

{% block conteudo_investimentos %}

<div class= "grid justify-center">
    <form action="" method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            {{form|crispy}}
        </fieldset>
        <button class="bg-amber-900 w-full rounded-md text-white text-lg" type="submit">Salvar</button>
    </form>
</div>

{% endblock %}

investimento/templates/config_ativos_listar.html
{% extends 'modelo_investimentos.html' %}

{% block titulo_pagina %}
    Ativos Cadastrados
{% endblock %}

{% block conteudo_investimentos %}

<div class= "grid justify-center">
        <div class=" grid grid-cols-3 grid-rows-2 gap-x-4 gap-y-0 bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"> 
            <p class="col-start-2 row-start-1 text-gray-500" >
                Novo ativo?
            </p>
            <a href="{% url 'investimento:config_ativos_novo' %}" 
            class=" col-start-2 row-start-2 border rounded-md py-1 px-4 bg-amber-900 text-white inline-block rounded"> 
            Cadastrar
            </a>
        </div>
</div>

{% load django_tables2 %}
{% render_table table %}

{% endblock %}

investimento/templates/configuracao_inicio.html
{% extends 'modelo_investimentos.html' %}

{% block titulo_pagina %}
    Configurações
{% endblock %}

{% block conteudo_investimentos %}

<h2 class="font-semibold text-xl mt-1"> Configurações do perfil </h2>
<p>Estas configurações afetam somente o perfil ativo</p>
<br>
<div class="flex flex-wrap justify-between space-x-2">
      
    <div class="max-w-xs rounded-lg bg-white shadow-lg">
        <div class="p-6">
          <h5
            class="mb-2 text-xl font-medium leading-tight text-neutral-800">
            Instituições Financeiras
          </h5>
          <p class="mb-4 text-base text-neutral-600">
            Cadastro de bancos e corretoras
          </p>
          <a href="{% url 'investimento:config_instituicao_financeira' %}"> 
              <button
              type="button"
              class="inline-block rounded bg-neutral-700 px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]"
              data-te-ripple-init
              data-te-ripple-color="light">
              Editar instituição
              </button>
          </a>
        </div>
      </div>

    <div class="max-w-xs rounded-lg bg-white shadow-lg">
      <div class="p-6">
        <h5
          class="mb-2 text-xl font-medium leading-tight text-neutral-800">
          Caixas
        </h5>
        <p class="mb-4 text-base text-neutral-600">
          Cadastro das categorias de alocação dos investimentos
        </p>
        <a href="{% url 'investimento:config_caixa' %}"> 
            <button
            type="button"
            class="inline-block rounded bg-neutral-700 px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]"
            data-te-ripple-init
            data-te-ripple-color="light">
            Editar caixa / alocação
            </button>
        </a>
      </div>
    </div>

</div>
<br>
<h2 class="font-semibold text-xl mt-1"> Configurações globais </h2>
<p>Estas configurações afetam todos os usuários</p>
<br>
<div class="flex flex-wrap justify-between space-x-2">
    
  <div class="max-w-xs rounded-lg bg-white shadow-lg">
      <div class="p-6">
        <h5
          class="mb-2 text-xl font-medium leading-tight text-neutral-800">
          Ativos
        </h5>
        <p class="mb-4 text-base text-neutral-600">
          Cadastro dos ativos (produtos de investimento)
        </p>
        <a href="{% url 'investimento:config_ativos' %}"> 
            <button
            type="button"
            class="inline-block rounded bg-neutral-700 px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]"
            data-te-ripple-init
            data-te-ripple-color="light">
            Editar ativo
            </button>
        </a>
      </div>
  </div>
  
  <div class="max-w-xs rounded-lg bg-white shadow-lg">
    <div class="p-6">
      <h5
        class="mb-2 text-xl font-medium leading-tight text-neutral-800">
        Administração
      </h5>
      <p class="mb-4 text-base text-neutral-600">
        Acesso ao painel de administração do sistema
      </p>
      <a href="{% url 'admin:index' %}"> 
          <button
          type="button"
          class="inline-block rounded bg-neutral-700 px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]"
          data-te-ripple-init
          data-te-ripple-color="light">
          Painel de administração
          </button>
      </a>
    </div>
  </div>
</div>

{% endblock %}

investimento/templates/invest_inicio.html
{% extends 'modelo_investimentos.html' %}


{% block titulo_pagina %}
    Investimentos
{% endblock %}

{% block conteudo_investimentos %}
Conteúdo aqui - teste oracle

{% endblock %}

investimento/templates/modelo_investimentos.html
{% extends 'modelo_area-logada.html' %}

{% block titulo %}
    Better Glauco - Investimentos
{% endblock %}


{% block conteudo %}
<div name="body-investimentos" class="grid grid-rows-[40px_1fr] gap-4 " >

    <section name="barra_titulo" class="row-start-1 
                                        grid grid-cols-[4fr_1fr] 
                                        bg-gray-100">
        <div name="titulo_pagina" class="col-start-1"> 
            <h1  class="font-semibold text-2xl mt-1">
                {% block titulo_pagina %}
                {% endblock %}
            </h1>
        </div>
        <form name = "selecionar_perfil" method="get" action="{% url 'investimento:home_investimento' %}" class="col-start-2 mt-1">
            <label for="perfil" class="form-label text-gray-500"> Perfil</label>
            <select name="perfil" class="form-select form-select-sm appearance-none
                                        w-2/5
                                        px-2
                                        py-1
                                        text-sm
                                        font-normal
                                        text-gray-700
                                        bg-white bg-clip-padding bg-no-repeat
                                        border border-solid border-gray-300
                                        rounded
                                        transition
                                        ease-in-out
                                        m-0
                                        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none">
              <option value="0">Selecionar perfil...</option>
                 {% for perfil in lista_perfis %}
                    {% if perfil.id == id_perfil_selecionado %}
                        <option selected value="{{ perfil.id }}">
                    {% else %}
                        <option value="{{ perfil.id }}">
                    {% endif %}
                    {{ perfil.nome }} </option>
                {% endfor %}
          </select>
          <button type="submit" class="form-check 
                                        bg-amber-900 w-2/5 rounded-md
                                        text-white text-lg" >
            Carregar
          </button>

        </form>
    </section>


</div>

<section name="conteudo_investimentos" class="row-start-2">
    {% block conteudo_investimentos %}
    {% endblock %}
</section>

{% endblock %}

investimento/templates/valor_compra.html
{% extends 'modelo_investimentos.html' %}

{% block titulo_pagina %}
Obter o valor recomendado para negociação do ativo
{% endblock %}


{% block conteudo_investimentos %}

<div class= "grid justify-center">
    <form method="get" action="{% url 'investimento:valor_compra' %}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        <div class="form-group grid grid-cols-4 grid-rows-3 gap-x-4 gap-y-0"> 
            <label for="ticket" class="col-start-1 row-start-1 form-label text-gray-500">Ticket do BDR</label>
            <input type="text" name="ticket" 
                                value="{{ request.GET.ticket }}"  
                                placeholder="ex: BIVB39" 
                                class= "col-start-1 row-start-2 form-control
                                        rounded-md border-2 border-gray-100 border-solid 
                                        text-black" />
            <label for="valor_US" class="col-start-2 row-start-1 form-label text-gray-500">Valor Origem (U$) <sup>1</sup></label>
            <input type="text" name="valor_US" 
                                value="{{ request.GET.valor_US }}"  
                                placeholder="ex: 0,0" 
                                class= "col-start-2 row-start-2 form-control
                                        rounded-md border-2 border-gray-100 border-solid 
                                        text-black" />
            <label for="valor_BDR" class="col-start-3 row-start-1 form-label text-gray-500">Valor BDR (R$)<sup>2</sup></label>
            <input type="text" name="valor_BDR" 
                                value="{{ request.GET.valor_BDR }}"  
                                placeholder="ex: 0,0" 
                                class= "col-start-3 row-start-2 form-control
                                        rounded-md border-2 border-gray-100 border-solid 
                                        text-black" />            
            <button type="submit" class="col-start-4 row-start-2 form-check 
                                        bg-amber-900 w-full mx-4 rounded-md
                                        text-white text-lg" >
                Pesquisar
            </button>
            <div class="col-start-1 col-span-4 row-start-3 text-gray-500 text-xs" >
              <p> <strong> (1) </strong> 
                Opcional. Preencher caso o valor do ativo no exterior esteja diferente do valor capturado pela API 
              </p>
              <p> <strong> (2) </strong> 
                Opcional. Valor de tela da corretora, para cálculo do Spread 
              </p>
            </div>
        </div>
    </form>
</div>

<div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
        <div class="overflow-hidden">
          <table class="min-w-full">
            <thead class="bg-amber-900 border-b">
              <tr>
                {% for operacao, linha in calculo_bdr.items %}
                  {% if not forloop.counter0 %}
                    <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
                      Operação
                    </th>
                    {% for chave in linha %}
                      <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
                            {{ chave }}
                      </th>
                    {% endfor %}
                  {% endif %}
                {% endfor %}
                </tr>
              </thead>
              <tbody>
                {% for operacao, linha in calculo_bdr.items %} 
                <tr class="bg-gray-100 border-b">
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                    {{ operacao }}
                  </td>
                  {% for chave, valor in linha.items %}
                      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                          {{ valor }}
                      </td>
                  {% endfor %}
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>



{% endblock %}