BetterGlauco/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_view
from django.urls import include, path

from .views import Contato, Homepage, Sobre

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Homepage.as_view(), name='homepage'),
    path('contato/', Contato.as_view(), name='contato'),
    path('invest/', include('investimento.urls', namespace='investimento')),
    path(
        'alocacao/',
        include('invest_alocacao.urls', namespace='invest_alocacao'),
    ),
    path(
        'operacao/',
        include('invest_operacao.urls', namespace='invest_operacao'),
    ),
    path(
        'atualizacao/',
        include('invest_atualizacao.urls', namespace='invest_atualizacao'),
    ),
    path(
        'login/',
        auth_view.LoginView.as_view(template_name='login.html'),
        name='login',
    ),
    path(
        'logout/',
        auth_view.LogoutView.as_view(template_name='logout.html'),
        name='logout',
    ),
    path('sobre/', Sobre.as_view(), name='sobre'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

invest_alocacao/urls.py
from django.urls import path

from .views import (
    ConfiguracaoMenu,
    ConfigurarAtivo,
    ConfigurarAtivoAlocacao,
    ConfigurarAtivoAlocacaoEditar,
    ConfigurarAtivoAlocacaoNovo,
    ConfigurarAtivoEditar,
    ConfigurarAtivoNovo,
    ConfigurarCaixa,
    ConfigurarCaixaEditar,
    ConfigurarCaixaNovo,
    ConfigurarInstituicaoFinanceira,
    ConfigurarInstituicaoFinanceiraEditar,
    ConfigurarInstituicaoFinanceiraNovo,
    ConfigurarSubCaixa,
    ConfigurarSubCaixaEditar,
    ConfigurarSubCaixaNovo,
    InicioAlocacao,
)

app_name = 'invest_alocacao'

urlpatterns = [
    path('', InicioAlocacao.as_view(), name='inicio_alocacao'),
    path('config/', ConfiguracaoMenu.as_view(), name='configuracao'),
    path('config/ativo/', ConfigurarAtivo.as_view(), name='config_ativos'),
    path(
        'config/ativo/novo/',
        ConfigurarAtivoNovo.as_view(),
        name='config_ativo_novo',
    ),
    path(
        'config/ativo/editar/<int:pk>',
        ConfigurarAtivoEditar.as_view(),
        name='config_ativo_editar',
    ),
    path(
        'config/ativo_alocacao/',
        ConfigurarAtivoAlocacao.as_view(),
        name='config_ativos_alocacao',
    ),
    path(
        'config/ativo_alocacao/novo/',
        ConfigurarAtivoAlocacaoNovo.as_view(),
        name='config_ativo_alocacao_novo',
    ),
    path(
        'config/ativo_alocacao/editar/<int:pk>',
        ConfigurarAtivoAlocacaoEditar.as_view(),
        name='config_ativo_alocacao_editar',
    ),
    path('config/caixa/', ConfigurarCaixa.as_view(), name='config_caixa'),
    path(
        'config/caixa/novo/',
        ConfigurarCaixaNovo.as_view(),
        name='config_caixa_novo',
    ),
    path(
        'config/caixa/editar/<int:pk>',
        ConfigurarCaixaEditar.as_view(),
        name='config_caixa_editar',
    ),
    path(
        'config/classe_ativo/',
        ConfigurarSubCaixa.as_view(),
        name='config_classe_ativo',
    ),
    path(
        'config/classe_ativo/novo/',
        ConfigurarSubCaixaNovo.as_view(),
        name='config_classe_ativo_novo',
    ),
    path(
        'config/classe_ativo/editar/<int:pk>',
        ConfigurarSubCaixaEditar.as_view(),
        name='config_classe_ativo_editar',
    ),
    path(
        'config/instituicao_financeira/',
        ConfigurarInstituicaoFinanceira.as_view(),
        name='config_instituicao_financeira',
    ),
    path(
        'config/instituicao_financeira/novo/',
        ConfigurarInstituicaoFinanceiraNovo.as_view(),
        name='config_instituicao_financeira_novo',
    ),
    path(
        'config/instituicao_financeira/editar/<int:pk>',
        ConfigurarInstituicaoFinanceiraEditar.as_view(),
        name='config_instituicao_financeira_editar',
    ),
]

invest_alocacao/models.py
# from django.db import models

# Create your models here.

invest_alocacao/forms.py
from django import forms

from investimento.models import (
    Ativo,
    AtivoPerfilCaixa,
    Caixa,
    ClasseAtivo,
    InstituicaoFinanceira,
)


class FormAtivo(forms.ModelForm):
    class Meta:
        model = Ativo
        fields = '__all__'
        widgets = {
            'desdobramento': forms.NumberInput(attrs={'step': 1}),
        }


class FormAtivoPerfilCaixa(forms.ModelForm):
    class Meta:
        model = AtivoPerfilCaixa
        fields = '__all__'
        exclude = ('perfil',)


class FormCaixa(forms.ModelForm):
    class Meta:
        model = Caixa
        fields = '__all__'
        exclude = ('perfil',)


class FormClasseAtivo(forms.ModelForm):
    class Meta:
        model = ClasseAtivo
        fields = '__all__'
        exclude = ('perfil',)


class FormInstituicaoFinanceira(forms.ModelForm):
    class Meta:
        model = InstituicaoFinanceira
        fields = '__all__'
        exclude = ('perfil',)

invest_alocacao/views.py
import django_tables2 as tables2
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import FormView, TemplateView, UpdateView
from django_filters.views import FilterView

from BetterGlauco.funcoes_auxiliares import Funcoes_auxiliares
from investimento.models import (
    Ativo,
    AtivoPerfilCaixa,
    Caixa,
    ClasseAtivo,
    InstituicaoFinanceira,
)
from investimento.tabelas import (
    TabelaAtivos,
    TabelaCaixas,
    TabelaClasseAtivo,
    TabelaInstituicaoFinanceira,
)

from .filtros import FiltroAtivo, FiltroClasseAtivo
from .forms import (
    FormAtivo,
    FormAtivoPerfilCaixa,
    FormCaixa,
    FormClasseAtivo,
    FormInstituicaoFinanceira,
)
from .tabela_alocacao import TabelaAlocacao


class InicioAlocacao(LoginRequiredMixin, TemplateView):
    template_name = 'alocacao_inicio.html'

    def get_context_data(self, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)
        tabela = TabelaAlocacao(id_perfil)

        context = super().get_context_data(**kwargs)
        context['id_perfil_selecionado'] = id_perfil
        context['tabela'] = tabela.getTabelaAlocacaoTeorica()
        return context


class ConfiguracaoMenu(LoginRequiredMixin, TemplateView):
    template_name = 'configuracao_inicio.html'

    def get_context_data(self, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)
        context = super().get_context_data(**kwargs)
        context['id_perfil_selecionado'] = id_perfil
        return context


class ConfigurarAtivo(
    LoginRequiredMixin, tables2.SingleTableMixin, FilterView
):
    filterset_class = FiltroAtivo
    queryset = Ativo.objects.order_by('ticket', 'nome')
    model = Ativo
    table_class = TabelaAtivos
    template_name = 'configuracao_filtrar_tabela.html'

    def get_context_data(self, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)
        context = super().get_context_data(**kwargs)
        context['titulo_pagina'] = 'Ativos Cadastrados'
        context['nome_parametro'] = 'ativo'
        context['url_insert'] = 'invest_alocacao:config_ativo_novo'
        context['id_perfil_selecionado'] = id_perfil
        mensagem = 'Cadastro geral. Alterações aqui afetarão todos os \
            usuários do sistema'
        messages.warning(self.request, mensagem)
        return context


class ConfigurarAtivoNovo(LoginRequiredMixin, FormView):
    form_class = FormAtivo
    template_name = 'configuracao_editar_tabela.html'

    def get_context_data(self, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)
        context = super().get_context_data(**kwargs)
        context['nome_parametro'] = 'ativo'
        context['id_perfil_selecionado'] = id_perfil
        mensagem = 'Cadastro geral. Alterações aqui afetarão todos os \
            usuários do sistema'
        messages.warning(self.request, mensagem)
        return context

    def form_valid(self, form, **kwargs):
        form.save()  # insere o item no BD
        messages.success(self.request, 'Ativo incluído com sucesso')
        return redirect('invest_alocacao:config_ativos')


class ConfigurarAtivoEditar(LoginRequiredMixin, UpdateView):
    form_class = FormAtivo
    model = Ativo
    template_name = 'configuracao_editar_tabela.html'

    def get_context_data(self, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)
        context = super().get_context_data(**kwargs)
        context['nome_parametro'] = 'ativo'
        context['id_perfil_selecionado'] = id_perfil
        mensagem = 'Cadastro geral. Alterações aqui afetarão todos os \
            usuários do sistema'
        messages.warning(self.request, mensagem)
        return context

    def form_valid(self, form, **kwargs):
        form.save()  # insere o item no BD
        messages.success(self.request, 'Ativo alterado com sucesso')
        return redirect('invest_alocacao:config_ativos')


class ConfigurarAtivoAlocacao(LoginRequiredMixin, TemplateView):
    template_name = 'alocacao_teorica_completa.html'

    def get_context_data(self, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)
        tabela = TabelaAlocacao(id_perfil)

        context = super().get_context_data(**kwargs)
        context['titulo_pagina'] = 'Ativos: cadastrar alocação'
        context['nome_parametro'] = 'alocacao ativo'
        context['url_insert'] = 'invest_alocacao:config_ativo_alocacao_novo'
        context['url_edit'] = 'invest_alocacao:config_ativo_alocacao_editar'
        context['id_perfil_selecionado'] = id_perfil
        context['tabela'] = tabela.getTabelaAlocacaoTeorica()
        return context


class ConfigurarAtivoAlocacaoNovo(LoginRequiredMixin, FormView):
    form_class = FormAtivoPerfilCaixa
    template_name = 'configuracao_editar_tabela.html'

    def get_context_data(self, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)
        context = super().get_context_data(**kwargs)
        context['nome_parametro'] = 'alocacao ativo'
        context['id_perfil_selecionado'] = id_perfil
        context['form'].fields[
            'subclasse'
        ].queryset = ClasseAtivo.objects.filter(caixa__perfil=id_perfil)
        context['form'].fields[
            'corretora'
        ].queryset = InstituicaoFinanceira.objects.filter(perfil=id_perfil)
        context['form'].fields['ativo'].queryset = Ativo.objects.order_by(
            'ticket', 'nome'
        )
        return context

    def form_valid(self, form, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)

        caixa = form.save(commit=False)
        caixa.perfil_id = id_perfil
        caixa.save()

        mensagem = 'Alocação do ativo cadastrada com sucesso'
        messages.warning(self.request, mensagem)
        return redirect('invest_alocacao:config_ativos_alocacao')


class ConfigurarAtivoAlocacaoEditar(LoginRequiredMixin, UpdateView):
    form_class = FormAtivoPerfilCaixa
    model = AtivoPerfilCaixa
    template_name = 'configuracao_editar_tabela.html'

    def get_context_data(self, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)
        context = super().get_context_data(**kwargs)
        context['nome_parametro'] = 'alocação ativo'
        context['id_perfil_selecionado'] = id_perfil
        context['form'].fields[
            'subclasse'
        ].queryset = ClasseAtivo.objects.filter(caixa__perfil=id_perfil)
        context['form'].fields[
            'corretora'
        ].queryset = InstituicaoFinanceira.objects.filter(perfil=id_perfil)
        return context

    def form_valid(self, form, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)

        caixa = form.save(commit=False)
        caixa.perfil_id = id_perfil
        caixa.save()

        mensagem = 'Alocação do ativo cadastrada com sucesso'
        messages.success(self.request, mensagem)
        return redirect('invest_alocacao:config_ativos_alocacao')


class ConfigurarCaixa(LoginRequiredMixin, tables2.SingleTableView):
    table_class = TabelaCaixas
    template_name = 'configuracao_listar_tabela.html'

    def get_queryset(self, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)
        return Caixa.objects.filter(perfil_id=id_perfil).order_by(
            'ordem_exibicao', 'nome'
        )

    def get_context_data(self, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)
        context = super().get_context_data(**kwargs)
        context['titulo_pagina'] = 'Caixas: Alocação por classe de ativo'
        context['nome_parametro'] = 'caixa'
        context['url_insert'] = 'invest_alocacao:config_caixa_novo'
        context['id_perfil_selecionado'] = id_perfil
        return context


class ConfigurarCaixaNovo(LoginRequiredMixin, FormView):
    form_class = FormCaixa
    template_name = 'configuracao_editar_tabela.html'

    def get_context_data(self, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)
        context = super().get_context_data(**kwargs)
        context['nome_parametro'] = 'caixa'
        context['id_perfil_selecionado'] = id_perfil
        return context

    def form_valid(self, form, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)

        caixa = form.save(commit=False)
        caixa.perfil_id = id_perfil
        caixa.save()

        messages.success(self.request, 'Caixa cadastrada com sucesso')
        return redirect('invest_alocacao:config_ativos_alocacao')


class ConfigurarCaixaEditar(LoginRequiredMixin, UpdateView):
    form_class = FormCaixa
    model = Caixa
    template_name = 'configuracao_editar_tabela.html'

    def get_context_data(self, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)
        context = super().get_context_data(**kwargs)
        context['nome_parametro'] = 'caixa'
        context['id_perfil_selecionado'] = id_perfil
        return context

    def form_valid(self, form, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)

        caixa = form.save(commit=False)
        caixa.perfil_id = id_perfil
        caixa.save()

        messages.success(self.request, 'Caixa atualizada com sucesso')
        return redirect('invest_alocacao:config_caixa')


class ConfigurarSubCaixa(
    LoginRequiredMixin, tables2.SingleTableMixin, FilterView
):
    table_class = TabelaClasseAtivo
    model = ClasseAtivo
    filterset_class = FiltroClasseAtivo
    template_name = 'configuracao_filtrar_tabela.html'

    def get_filterset(self, *args, **kwargs):

invest_alocacao/templates/alocacao_inicio.html
{% extends 'modelo_investimentos.html' %}

{% block titulo_pagina %}
    Alocação
{% endblock %}

{% block conteudo_investimentos %}

<h2 class="font-semibold text-xl mt-1"> Configuração </h2>
<p>Estas configurações afetam somente o perfil ativo</p>
<br>
<div class="flex flex-wrap justify-between space-x-2">

  <div class="max-w-xs rounded-lg bg-white shadow-lg">
    <div class="p-6">
      <h5
        class="mb-2 text-xl font-medium leading-tight text-neutral-800">
        1 - Caixas
      </h5>
      <p class="mb-4 text-base text-neutral-600">
        Cadastro das categorias de alocação dos investimentos
      </p>
      <a href="{% url 'invest_alocacao:config_caixa' %}"> 
          <button
          type="button"
          class="inline-block rounded bg-neutral-700 px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]"
          data-te-ripple-init
          data-te-ripple-color="light">
          Editar caixa / alocação
          </button>
      </a>
    </div>
  </div>

  <div class="max-w-xs rounded-lg bg-white shadow-lg">
    <div class="p-6">
      <h5
        class="mb-2 text-xl font-medium leading-tight text-neutral-800">
        2 - Sub Caixas
      </h5>
      <p class="mb-4 text-base text-neutral-600">
        Cadastro de classes de ativos
      </p>
      <a href="{% url 'invest_alocacao:config_classe_ativo' %}"> 
          <button
          type="button"
          class="inline-block rounded bg-neutral-700 px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]"
          data-te-ripple-init
          data-te-ripple-color="light">
          Editar classe
          </button>
      </a>
    </div>
  </div>  

  <div class="max-w-xs rounded-lg bg-white shadow-lg">
      <div class="p-6">
        <h5
          class="mb-2 text-xl font-medium leading-tight text-neutral-800">
          3 - Instituições Financeiras
        </h5>
        <p class="mb-4 text-base text-neutral-600">
          Cadastro de bancos e corretoras
        </p>
        <a href="{% url 'invest_alocacao:config_instituicao_financeira' %}"> 
            <button
            type="button"
            class="inline-block rounded bg-neutral-700 px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]"
            data-te-ripple-init
            data-te-ripple-color="light">
            Editar instituição
            </button>
        </a>
      </div>
    </div>

    <div class="max-w-xs rounded-lg bg-white shadow-lg">
      <div class="p-6">
        <h5
          class="mb-2 text-xl font-medium leading-tight text-neutral-800">
          4 - Alocar ativos nas caixas
        </h5>
        <p class="mb-4 text-base text-neutral-600">
          Selecionar os ativos que compõe cada classe de ativo / caixa de investimento
        </p>
        <a href="{% url 'invest_alocacao:config_ativos_alocacao' %}"> 
            <button
            type="button"
            class="inline-block rounded bg-neutral-700 px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]"
            data-te-ripple-init
            data-te-ripple-color="light">
            Editar alocação
            </button>
        </a>
      </div>
    </div>

</div>

<br><br>
<h2 class="font-semibold text-xl mt-1"> Alocação teórica</h2>
<br>

<div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full">
          {% for id_linha, linha in tabela.items %}
            {% if id_linha == 'header'%}
              <thead class="bg-amber-900 border-b">
                <tr>
                      {% for chave, valor in linha.items %}
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
                              {{ chave }}
                        </th>
                      {% endfor %}
                </tr>
              </thead>
              <tbody>
            {% elif 'Total' in id_linha %}
                  {% if forloop.counter|divisibleby:2 %}
                    <tr class="bg-gray-100 border-b">
                  {% else %}
                    <tr class="border-b"></tr>
                  {% endif %} 
                  {% for chave, valor in linha.items %}
                      <td class="px-6 py-4 whitespace-nowrap text-sm font-bold text-gray-900">
                          {{ valor }}
                      </td>
                  {% endfor %}
                </tr>     
            {% else %}
              {% if forloop.counter|divisibleby:2 %}
                <tr class="bg-gray-100 border-b">
              {% else %}
                <tr class="border-b"></tr>
              {% endif %} 
              {% for chave, valor in linha.items %}
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                        {{ valor }}
                    </td>
                {% endfor %}
              </tr> 
            {% endif %}
          {% endfor %}  
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>




{% endblock %}

invest_alocacao/templates/alocacao_teorica_completa.html
{% extends 'modelo_investimentos.html' %}

{% block titulo_pagina %}
  {{ titulo_pagina }}
{% endblock %}


{% block conteudo_investimentos %}

<div class= "grid justify-center">
  <div class=" grid grid-cols-3 grid-rows-2 gap-x-4 gap-y-0 bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"> 
      <p class="col-start-2 row-start-1 text-gray-500" >
          Adicionar {{ nome_parametro }}?
      </p>
      <a href="{% url url_insert %}" 
      class=" col-start-2 row-start-2 border rounded-md py-1 px-4 bg-amber-900 text-white inline-block rounded"> 
          Cadastrar
      </a>
  </div>
</div>


<div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full">
          {% for id_linha, linha in tabela.items %}
            {% if id_linha == 'header'%}
              <thead class="bg-amber-900 border-b">
                <tr>
                      {% for chave, valor in linha.items %}
                        <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
                              {{ chave }}
                        </th>
                      {% endfor %}
                      <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
                        Atualizar
                      </th>
                </tr>
              </thead>
              <tbody>
            {% elif  'Total' in id_linha %}
                  {% if forloop.counter|divisibleby:2 %}
                    <tr class="bg-gray-100 border-b">
                  {% else %}
                    <tr class="border-b"></tr>
                  {% endif %} 
                  {% for chave, valor in linha.items %}
                      <td class="px-6 py-4 whitespace-nowrap text-sm font-bold text-gray-900">
                          {{ valor }}
                      </td>
                  {% endfor %}
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-bold text-gray-900">
                      
                    </td>
                </tr>     
            {% else %}
              {% if forloop.counter|divisibleby:2 %}
                <tr class="bg-gray-100 border-b">
              {% else %}
                <tr class="border-b"></tr>
              {% endif %} 
              {% for chave, valor in linha.items %}
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                        {{ valor }}
                    </td>
                {% endfor %}
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                    <a href="{% url url_edit id_linha %}" 
                    class=" col-start-2 row-start-2 border rounded-md py-1 px-4 bg-amber-900 text-white inline-block rounded"> 
                        Editar
                    </a>
                  </td>
              </tr> 
            {% endif %}
          {% endfor %}  
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>



{% endblock %}

invest_alocacao/templates/configuracao_editar_tabela.html
{% extends 'modelo_investimentos.html' %}
{% load crispy_forms_tags %}

{% block titulo_pagina %}
    {% if form.instance.pk %}
            Atualizar {{ nome_parametro }}
    {% else %}
            Cadastrar {{ nome_parametro }}
    {% endif %}
{% endblock %}

{% block conteudo_investimentos %}

<div class= "grid justify-center">
    <form action="" method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            {{form|crispy}}
        </fieldset>
        <button class="bg-amber-900 w-full rounded-md text-white text-lg" type="submit">Salvar</button>
    </form>
</div>

{% endblock %}

invest_alocacao/templates/configuracao_listar_tabela.html
{% extends 'modelo_investimentos.html' %}

{% block titulo_pagina %}
    {{ titulo_pagina }}
{% endblock %}

{% block conteudo_investimentos %}

<div class= "grid justify-center">
        <div class=" grid grid-cols-3 grid-rows-2 gap-x-4 gap-y-0 bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"> 
            <p class="col-start-2 row-start-1 text-gray-500" >
                Adicionar {{ nome_parametro }}?
            </p>
            <a href="{% url url_insert %}" 
            class=" col-start-2 row-start-2 border rounded-md py-1 px-4 bg-amber-900 text-white inline-block rounded"> 
                Cadastrar
            </a>
        </div>
</div>

{% load django_tables2 %}
{% render_table table %}

{% endblock %}