BetterGlauco/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_view
from django.urls import include, path

from .views import Contato, Homepage, Sobre

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Homepage.as_view(), name='homepage'),
    path('contato/', Contato.as_view(), name='contato'),
    path('invest/', include('investimento.urls', namespace='investimento')),
    path(
        'alocacao/',
        include('invest_alocacao.urls', namespace='invest_alocacao'),
    ),
    path(
        'operacao/',
        include('invest_operacao.urls', namespace='invest_operacao'),
    ),
    path(
        'atualizacao/',
        include('invest_atualizacao.urls', namespace='invest_atualizacao'),
    ),
    path(
        'login/',
        auth_view.LoginView.as_view(template_name='login.html'),
        name='login',
    ),
    path(
        'logout/',
        auth_view.LogoutView.as_view(template_name='logout.html'),
        name='logout',
    ),
    path('sobre/', Sobre.as_view(), name='sobre'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

invest_alocacao/urls.py
from django.urls import path

from .views import (
    ConfiguracaoMenu,
    ConfigurarAtivo,
    ConfigurarAtivoAlocacao,
    ConfigurarAtivoAlocacaoEditar,
    ConfigurarAtivoAlocacaoNovo,
    ConfigurarAtivoEditar,
    ConfigurarAtivoNovo,
    ConfigurarCaixa,
    ConfigurarCaixaEditar,
    ConfigurarCaixaNovo,
    ConfigurarInstituicaoFinanceira,
    ConfigurarInstituicaoFinanceiraEditar,
    ConfigurarInstituicaoFinanceiraNovo,
    ConfigurarSubCaixa,
    ConfigurarSubCaixaEditar,
    ConfigurarSubCaixaNovo,
    InicioAlocacao,
)

app_name = 'invest_alocacao'

urlpatterns = [
    path('', InicioAlocacao.as_view(), name='inicio_alocacao'),
    path('config/', ConfiguracaoMenu.as_view(), name='configuracao'),
    path('config/ativo/', ConfigurarAtivo.as_view(), name='config_ativos'),
    path(
        'config/ativo/novo/',
        ConfigurarAtivoNovo.as_view(),
        name='config_ativo_novo',
    ),
    path(
        'config/ativo/editar/<int:pk>',
        ConfigurarAtivoEditar.as_view(),
        name='config_ativo_editar',
    ),
    path(
        'config/ativo_alocacao/',
        ConfigurarAtivoAlocacao.as_view(),
        name='config_ativos_alocacao',
    ),
    path(
        'config/ativo_alocacao/novo/',
        ConfigurarAtivoAlocacaoNovo.as_view(),
        name='config_ativo_alocacao_novo',
    ),
    path(
        'config/ativo_alocacao/editar/<int:pk>',
        ConfigurarAtivoAlocacaoEditar.as_view(),
        name='config_ativo_alocacao_editar',
    ),
    path('config/caixa/', ConfigurarCaixa.as_view(), name='config_caixa'),
    path(
        'config/caixa/novo/',
        ConfigurarCaixaNovo.as_view(),
        name='config_caixa_novo',
    ),
    path(
        'config/caixa/editar/<int:pk>',
        ConfigurarCaixaEditar.as_view(),
        name='config_caixa_editar',
    ),
    path(
        'config/classe_ativo/',
        ConfigurarSubCaixa.as_view(),
        name='config_classe_ativo',
    ),
    path(
        'config/classe_ativo/novo/',
        ConfigurarSubCaixaNovo.as_view(),
        name='config_classe_ativo_novo',
    ),
    path(
        'config/classe_ativo/editar/<int:pk>',
        ConfigurarSubCaixaEditar.as_view(),
        name='config_classe_ativo_editar',
    ),
    path(
        'config/instituicao_financeira/',
        ConfigurarInstituicaoFinanceira.as_view(),
        name='config_instituicao_financeira',
    ),
    path(
        'config/instituicao_financeira/novo/',
        ConfigurarInstituicaoFinanceiraNovo.as_view(),
        name='config_instituicao_financeira_novo',
    ),
    path(
        'config/instituicao_financeira/editar/<int:pk>',
        ConfigurarInstituicaoFinanceiraEditar.as_view(),
        name='config_instituicao_financeira_editar',
    ),
]

invest_atualizacao/urls.py
from django.urls import path

from .views import (
    DividendoEditar,
    DividendoNovo,
    DividendosInicio,
    InicioAtualizacao,
    PosicaoIndividualBolsa,
    PosicaoIndividualBolsaEditar,
    PosicaoIndividualBolsaNova,
    PosicaoIndividualFundo,
    PosicaoIndividualFundoEditar,
    PosicaoIndividualFundoNova,
)

app_name = 'invest_atualizacao'

urlpatterns = [
    path('', InicioAtualizacao.as_view(), name='inicio_atualizacao'),
    path('dividendos/', DividendosInicio.as_view(), name='dividendos'),
    path('dividendos/novo/', DividendoNovo.as_view(), name='dividendos_novo'),
    path(
        'dividendos/editar/<int:pk>',
        DividendoEditar.as_view(),
        name='dividendos_editar',
    ),
    path(
        'individual/bolsa/',
        PosicaoIndividualBolsa.as_view(),
        name='posicao_individual_bolsa',
    ),
    path(
        'individual/bolsa/novo/',
        PosicaoIndividualBolsaNova.as_view(),
        name='posicao_individual_bolsa_nova',
    ),
    path(
        'individual/bolsa/editar/<int:pk>',
        PosicaoIndividualBolsaEditar.as_view(),
        name='posicao_individual_bolsa_editar',
    ),
    path(
        'individual/fundo/',
        PosicaoIndividualFundo.as_view(),
        name='posicao_individual_fundo',
    ),
    path(
        'individual/fundo/novo/',
        PosicaoIndividualFundoNova.as_view(),
        name='posicao_individual_fundo_nova',
    ),
    path(
        'individual/fundo/editar/<int:pk>',
        PosicaoIndividualFundoEditar.as_view(),
        name='posicao_individual_fundo_editar',
    ),
]

invest_operacao/urls.py
from django.urls import path

from .views import (
    InicioOperacao,
    OperacaoIndividual,
    OperacaoIndividualBolsaNova,
    OperacaoIndividualEditar,
    OperacaoIndividualFundoNova,
    RegistraNotaCorretagem,
)

app_name = 'invest_operacao'

urlpatterns = [
    path('', InicioOperacao.as_view(), name='inicio_operacao'),
    path(
        'nota_corretora/',
        RegistraNotaCorretagem.as_view(),
        name='nota_corretagem',
    ),
    path(
        'nota_corretora/<int:id_linha>',
        RegistraNotaCorretagem.as_view(),
        name='nota_corretagem',
    ),
    path(
        'individual/', OperacaoIndividual.as_view(), name='operacao_individual'
    ),
    path(
        'individual/bolsa/novo/',
        OperacaoIndividualBolsaNova.as_view(),
        name='operacao_individual_bolsa_nova',
    ),
    path(
        'individual/fundo/novo/',
        OperacaoIndividualFundoNova.as_view(),
        name='operacao_individual_fundo_nova',
    ),
    path(
        'individual/editar/<int:pk>',
        OperacaoIndividualEditar.as_view(),
        name='operacao_individual_editar',
    ),
]

investimento/urls.py
from django.urls import path

from .views import (
    Ajuda,
    HomeInvestimento,
    Imposto_bdr_usa,
    Valor_compra,
)

app_name = 'investimento'

urlpatterns = [
    path('', HomeInvestimento.as_view(), name='home_investimento'),
    path('help/', Ajuda.as_view(), name='ajuda_inicio'),
    path(
        'imposto-dividendo-bdr/',
        Imposto_bdr_usa.as_view(),
        name='imposto_dividendo_bdr',
    ),
    path('valor-compra/', Valor_compra.as_view(), name='valor_compra'),
]

templates/contato.html
{% extends 'modelo_aberto.html' %}

{% block titulo %}
    Better Glauco
{% endblock %}

{% block conteudo %}


<h1>Contato</h1>
Formulário para contato




{% endblock %}

templates/footer_aberto.html
<footer class="text-center">
	<p>
		2023: <a
			href="https://creativecommons.org/licenses/by-nc/4.0/deed.pt_BR" class="text-orange-700 underline decoration-transparent hover:decoration-inherit transition duration-300 ease-in-out">CC
			BY-NC 4.0</a>
	</p>
</footer>

templates/index.html
{% extends 'modelo_aberto.html' %}

{% block titulo %}
    Better Glauco
{% endblock %}

{% block conteudo %}


<h1  class="font-semibold text-2xl mb-4">
    Olá!
</h1>

<p class="text-base mb-4">Para saber mais sobre o sistema Better Glauco, acesse a página <a href="{% url 'sobre' %}" class="text-orange-700 underline decoration-transparent hover:decoration-inherit transition duration-300 ease-in-out"> sobre</a>. </p>

<p class="text-base mb-4">O código fonte e informações para desenvolvedores estão disponíveis no <a href="https://github.com/divirjo/-BetterGlauco" class="text-orange-700 underline decoration-transparent hover:decoration-inherit transition duration-300 ease-in-out"> Git Hub</a>. </p>

<p class="text-base mb-4">O acesso às areas internas depende de prévio cadastro. Se você possui usuário e senha <a href="{% url 'login' %}" class="text-orange-700 underline decoration-transparent hover:decoration-inherit transition duration-300 ease-in-out"> acesse aqui</a>. </p>



{% endblock %}

templates/login.html
{% extends 'modelo_aberto.html' %}

{% load tailwind_filters %}

{% block titulo %}
    Better Glauco
{% endblock %}

{% block conteudo %}


<h1  class="font-semibold text-2xl mb-4"> 
    Entrar
</h1>

<div class= "flex justify-center">
    <form method="post" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Faça Login para continuar</legend>
            {{form|crispy}}
        </fieldset>
        <button class="bg-amber-900 py-1 my-2 px-3 w-full text-white md:text-lg rounded-md" type="submit">
            Entrar
        </button>
    </form>
</div>





{% endblock %}

templates/logout.html
{% extends 'modelo_aberto.html' %}

{% block titulo %}
    Better Glauco
{% endblock %}

{% block conteudo %}


<h1  class="font-semibold text-2xl mb-4">
    Logout
</h1>

<p class="text-base mb-4">Você foi desconectado do sistema com sucesso. Até breve.</p>



<a href="{% url 'login' %}">
    <button class="bg-amber-900 py-1 px-3 text-white md:text-lg rounded-md">
        Entrar
    </button>
</a>


{% endblock %}

templates/menu_aberto.html
{% load static %}

<header id="headerInicial" class="col-start-2 rol-start-1 text-center">
    <a href="/" class="">
        <img id="logoInicio" class =" w-1/5 mx-auto" src="{% static 'imagens/logo_color.svg' %}"
            alt="Logo better glauco">
        <p id="marcaInicio" class ="text-xl font-cursive " >Better Glauco</p>
    </a>
</header>
<nav id="menuSuperior" class="col-start-3 rol-start-1 text-right">
	<ul class="list-none">
		<li class="inline" >
            <a href="{% url 'login' %}" class="text-orange-700 underline decoration-transparent hover:decoration-inherit transition duration-300 ease-in-out"> 
                Entrar
            </a>
        </li>
		<li class="inline">
            <a href="{% url 'sobre' %}" class="text-orange-700 underline decoration-transparent hover:decoration-inherit transition duration-300 ease-in-out"> 
                Sobre
            </a>
        </li>
		<li class="inline">
            <a href="{% url 'contato' %}" class="text-orange-700 underline decoration-transparent hover:decoration-inherit transition duration-300 ease-in-out"> 
                Contato
            </a>
        </li>
	</ul>
</nav>

templates/menu_area-logada.html
{% load static %}

<header class="row-start-1 text-center">
	<a href="{% url 'investimento:home_investimento' %}"
	 	class="">
		<img id="logo" class =" w-3/5 mx-auto" src="{% static 'imagens/logo_color.svg' %}" alt="Logo better glauco">
		<p id="marca" class ="text-sm font-cursive ">Better Glauco</p>
	</a>

</header>
<nav class="row-start-2 text-sm font-semibold">
	<ul class="list-none">
		<li> Investimentos: </li>
		<li class="font-normal">
			<a href="{% url 'invest_alocacao:inicio_alocacao' %}"
				class=" underline decoration-transparent 
						hover:decoration-inherit hover:text-orange-700 transition duration-300 ease-in-out"> 
				1. Alocação
			</a>
		</li>
		<li class="font-normal">
			<a href="{% url 'invest_operacao:inicio_operacao' %}"
				class=" underline decoration-transparent 
						hover:decoration-inherit hover:text-orange-700 transition duration-300 ease-in-out"> 
				2. Registrar compra 
			</a>
		</li>
		<li class="font-normal">
			<a href="{% url 'invest_atualizacao:inicio_atualizacao' %}"
				class=" underline decoration-transparent 
						hover:decoration-inherit hover:text-orange-700 transition duration-300 ease-in-out"> 
				3. Atualização 
			</a>
		</li>
		<li class="font-normal">
			<a href=""
				class=" underline decoration-transparent 
						hover:decoration-inherit hover:text-orange-700 transition duration-300 ease-in-out"> 
				4. Análise 
			</a>
		</li>
		<li>
			BDR
		</li>
			<ul class="list-none font-normal">
				<li>
					<a href="{% url 'investimento:valor_compra' %}" 
						class=" underline decoration-transparent 
								hover:decoration-inherit hover:text-orange-700 transition duration-300 ease-in-out"> 
						1.Valor Compra
					</a>
				</li>
				<li>
					<a href="{% url 'investimento:imposto_dividendo_bdr' %}" 
						class=" underline decoration-transparent 
								hover:decoration-inherit hover:text-orange-700 transition duration-300 ease-in-out"> 
						2. Imposto dividendos
					</a>
				</li>
			</ul>

	</ul>
</nav>
<section id="controles" class="row-start-3">

	<a href="{% url 'logout' %}">
		<span title="Sair">
			<ion-icon name="close-circle"></ion-icon>
		</span>
	</a>
	<a href="{% url 'investimento:ajuda_inicio' %}"> 
		<span title="Ajuda">
			<ion-icon name="help-circle"></ion-icon>
		</span>
	</a>
	<a href="{% url 'invest_alocacao:configuracao' %}"> 
		<span title="Configurar">
			<ion-icon name="build"></ion-icon>
		</span>
	</a>
</section>

templates/modelo_aberto.html
{% extends 'modelo_principal.html' %}

{% block content %}
<div name="body-formtação" class="grid grid-cols-3 grid-rows-[1/4_1fr_1fr] gap-4">

    {% include 'menu_aberto.html' %}

    <main class="col-start-1 col-span-4 rol-start-2">
        {% block conteudo %}
        {% endblock %}
    </main>

    <section id="footer" class="col-start-1 col-span-4 rol-start-3">
        {% include 'footer_aberto.html' %}
    </section>


</div>
{% endblock %}

templates/modelo_area-logada.html
{% extends 'modelo_principal.html' %}

{% block content %}
<div name="body-formatacao" class="grid grid-cols-[150px_1fr] grid-rows-[50px_1fr_50px] gap-4 " >

    <section id="lateral" class="col-start-1 row-start-1 row-span-2 grid grid-rows-[1/10_1fr_1/10] bg-orange-200">
        {% include 'menu_area-logada.html' %}
    </section>

    <section id="mensagens" class="col-start-2 row-start-1">
        {% if messages %}
            <ul class="px-4 py-4">
                {% for message in messages %}
                    <li 
                        {% if message.tags == 'debug' %} 
                            class=" bg-orange-600 text-white font-semibold "
                        {% endif %}
                        {% if message.tags == 'error' %} 
                            class=" bg-red-200 font-semibold"
                        {% endif %}
                        {% if message.tags == 'info' %} 
                            class=" bg-sky-300 font-semibold"
                        {% endif %}
                        {% if message.tags == 'warning' %} 
                        class=" bg-amber-200 font-semibold"
                        {% endif %}
                        {% if message.tags == 'success' %} 
                        class=" bg-green-300 font-semibold"
                        {% endif %} 
                        >
                        {{ message }}
                    </li>
                {% endfor %}    
            </ul>
        {% endif %}
    </section>
    
    
    <main class="col-start-2 row-start-2">
        {% block conteudo %}
        {% endblock %}
    </main>

    <section id="footer" class="col-start-1 col-span-2 row-start-3">
        {% include 'footer_aberto.html' %}
    </section>

</div>
{% endblock %}

{% block javascript %}
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
{% endblock %}

templates/modelo_principal.html
<!DOCTYPE html>
{% load static %}

<html lang="pt-br">

  <head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-5GLTKKCH0F"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-5GLTKKCH0F');
    </script>
    <title>
        {% block titulo %}
        {% endblock %}
    </title>
    <meta charset="UTF-8">
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
          theme: {
            extend: {
                fontFamily: {
                    sans: ['Verdana', 'Tahoma', 'sans-serif' ,'ui-sans-serif'],
                    cursive: ['"Dancing Script"','cursive','sans-serif']
              }
            }
          }
        }
      </script>
      <link rel="stylesheet" href="{% static 'css/main.css' %}">
      <link rel="shortcut icon" type="imagex/png" href="{% static 'imagens/logo_color.ico' %}">


    {% block headCSS %}
    {% endblock %}

  </head>

  <body class="font-sans">
      {% block content %}
      {% endblock %}

      {% block javascript %}
      {% endblock %}
  </body>

</html>

templates/sobre.html
{% extends 'modelo_aberto.html' %}

{% block titulo %}
    Better Glauco
{% endblock %}

{% block conteudo %}


<h1 class="font-semibold text-2xl mb-4">
    O que é o Better Glauco
</h1>

<p class="text-base mb-4">Better Glauco é um sistema para controle de orçamento doméstico
    e de investimentos de pessoas físicas.</p>
<p class="text-base mb-4">Visamos propiciar uma visão a longo prazo das finanças
    pessoais, ajudar as pessoas a saírem das dívidas e passarem a
    investir para obter renda ou atingir objetivos de longo prazo.</p>
<p class="text-base mb-4">Realizamos uma consolidação dos investimentos pessoais, focando
    no desempenho e balanceamento da carteira. Também disponibilizamos um
    controle de orçamento doméstico prético e poderoso para analisar os
    dados, auxiliando o usuário a destinar parte da renda aos aportes nos
    investimentos.</p>
<p class="text-base mb-4">
    No controle de investimentos, inicialmente a base teórica será a
    divisão dos ativos em caixas (renda fixa, variável, reserva de
    emergência etc.), método da <a href="https://www.instagram.com/seabraluciana/" class="text-orange-700 underline decoration-transparent hover:decoration-inherit transition duration-300 ease-in-out">Luciana
        Seabra</a>, baseada nas práticas dos
    principais alocadores de recursos em atividade.
</p>
<p class="text-base mb-4" >É possível no cenário futuro de open banking obter integrações
    que aprimorem a privacidade do usuário, o que pode permitir a
    disponibilização de um perfil em que o usuário forneça mais
    informações pessoais em troca de uma maior integração com os
    sistemas, sincronizando dados automaticamente.</p>



{% endblock %}