BetterGlauco/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_view
from django.urls import include, path

from .views import Contato, Homepage, Sobre

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Homepage.as_view(), name='homepage'),
    path('contato/', Contato.as_view(), name='contato'),
    path('invest/', include('investimento.urls', namespace='investimento')),
    path(
        'alocacao/',
        include('invest_alocacao.urls', namespace='invest_alocacao'),
    ),
    path(
        'operacao/',
        include('invest_operacao.urls', namespace='invest_operacao'),
    ),
    path(
        'atualizacao/',
        include('invest_atualizacao.urls', namespace='invest_atualizacao'),
    ),
    path(
        'login/',
        auth_view.LoginView.as_view(template_name='login.html'),
        name='login',
    ),
    path(
        'logout/',
        auth_view.LogoutView.as_view(template_name='logout.html'),
        name='logout',
    ),
    path('sobre/', Sobre.as_view(), name='sobre'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

invest_operacao/urls.py
from django.urls import path

from .views import (
    InicioOperacao,
    OperacaoIndividual,
    OperacaoIndividualBolsaNova,
    OperacaoIndividualEditar,
    OperacaoIndividualFundoNova,
    RegistraNotaCorretagem,
)

app_name = 'invest_operacao'

urlpatterns = [
    path('', InicioOperacao.as_view(), name='inicio_operacao'),
    path(
        'nota_corretora/',
        RegistraNotaCorretagem.as_view(),
        name='nota_corretagem',
    ),
    path(
        'nota_corretora/<int:id_linha>',
        RegistraNotaCorretagem.as_view(),
        name='nota_corretagem',
    ),
    path(
        'individual/', OperacaoIndividual.as_view(), name='operacao_individual'
    ),
    path(
        'individual/bolsa/novo/',
        OperacaoIndividualBolsaNova.as_view(),
        name='operacao_individual_bolsa_nova',
    ),
    path(
        'individual/fundo/novo/',
        OperacaoIndividualFundoNova.as_view(),
        name='operacao_individual_fundo_nova',
    ),
    path(
        'individual/editar/<int:pk>',
        OperacaoIndividualEditar.as_view(),
        name='operacao_individual_editar',
    ),
]

invest_operacao/models.py
# from django.db import models

# Create your models here.

invest_operacao/views.py
from datetime import datetime
from decimal import Decimal

import django_tables2 as tables2
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Value
from django.db.models.functions import Concat
from django.shortcuts import redirect
from django.views.generic import FormView, UpdateView
from django_filters.views import FilterView
from django_tables2.paginators import LazyPaginator

from BetterGlauco.funcoes_auxiliares import Funcoes_auxiliares
from invest_atualizacao.cotas_ativo import CotaAtivo
from investimento.models import AtivoPerfilCaixa, ExtratoOperacao

from .filtros_operacoes import FiltroOperacaoAtivo
from .forms_operacoes import (
    FormExtratoOperacaoBolsa,
    FormExtratoOperacaoFundo,
    FormOperacaoNotaCorretagem,
)
from .nota_corretagem import registrar_nota_corretagem
from .tabelas import TabelaExtratoOperacoes, tabelaNotaCorretagem


class InicioOperacao(LoginRequiredMixin, tables2.SingleTableView):
    paginator_class = LazyPaginator
    table_class = TabelaExtratoOperacoes
    template_name = 'operacao_inicio.html'

    def get_queryset(self, **kwargs):
        return ExtratoOperacao.objects.filter(
            ativo_perfil_caixa__subclasse__caixa__perfil=Funcoes_auxiliares.get_perfil_ativo(
                self.request, **kwargs
            )
        ).order_by('-data')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['id_perfil_selecionado'] = Funcoes_auxiliares.get_perfil_ativo(
            self.request, **kwargs
        )

        return context


class OperacaoIndividual(
    LoginRequiredMixin, tables2.SingleTableMixin, FilterView
):
    filterset_class = FiltroOperacaoAtivo
    paginator_class = LazyPaginator
    table_class = TabelaExtratoOperacoes
    template_name = 'operacao_historico_ativo.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['id_perfil_selecionado'] = Funcoes_auxiliares.get_perfil_ativo(
            self.request, **kwargs
        )
        context['titulo_pagina'] = 'Histórico de Operações'
        return context

    def get_filterset(self, *args, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)
        fs = super().get_filterset(*args, **kwargs)
        fs.filters[
            'ativo_perfil_caixa'
        ].field.queryset = AtivoPerfilCaixa.objects.filter(
            subclasse__caixa__perfil=id_perfil
        ).order_by('ativo__ticket', 'ativo__nome')
        return fs

    def get_queryset(self, **kwargs):
        return ExtratoOperacao.objects.filter(
            ativo_perfil_caixa__subclasse__caixa__perfil=Funcoes_auxiliares.get_perfil_ativo(
                self.request, **kwargs
            )
        ).order_by('-data')


class OperacaoIndividualBolsaNova(LoginRequiredMixin, FormView):
    form_class = FormExtratoOperacaoBolsa
    template_name = 'registrar_operacao_individual.html'

    def get_context_data(self, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)

        query_ativos = AtivoPerfilCaixa.objects.filter(
            subclasse__caixa__perfil=id_perfil, ativo__cota_bolsa=True
        ).order_by('ativo__ticket', 'ativo__nome')

        context = super().get_context_data(**kwargs)
        context['id_perfil_selecionado'] = id_perfil
        context['nome_parametro'] = 'compra ou venda de ativo listado em bolsa'
        context['form'].fields['ativo_perfil_caixa'].queryset = query_ativos
        return context

    def form_valid(self, form, **kwargs):
        operacao = form.save(commit=False)
        operacao.save()
        messages.success(
            self.request,
            'Operação de {} cadastrada com sucesso'.format(
                form.cleaned_data['operacao']
            ),
        )
        return redirect('invest_operacao:operacao_individual')


class OperacaoIndividualFundoNova(LoginRequiredMixin, FormView):
    form_class = FormExtratoOperacaoFundo
    template_name = 'registrar_operacao_individual.html'

    def get_context_data(self, **kwargs):
        id_perfil = Funcoes_auxiliares.get_perfil_ativo(self.request, **kwargs)

        query_ativos = AtivoPerfilCaixa.objects.filter(
            subclasse__caixa__perfil=id_perfil, ativo__cota_bolsa=False
        ).order_by(
            'subclasse__caixa__nome',
        )

        context = super().get_context_data(**kwargs)
        context['id_perfil_selecionado'] = id_perfil
        context['nome_parametro'] = 'compra ou venda de ativo não listado em \
            bolsa (fundos)'
        context['form'].fields['ativo_perfil_caixa'].queryset = query_ativos
        mensagem = 'Atualize o valor atual dos ativos antes de \
            cadastrar uma operação, para viabilizar \
            o adequado cálculo da quantidade de cotas'
        messages.info(self.request, mensagem)
        return context

    def form_valid(self, form, **kwargs):
        ativo_selecionado = form.cleaned_data['ativo_perfil_caixa'].ativo_id
        cotas_ativo = CotaAtivo(ativo_selecionado)
        valor_operacao = form.cleaned_data['valor_total']
        valor_cota = cotas_ativo.valorMaisRecente()

        operacao = form.save(commit=False)
        operacao.valor_unitario = valor_cota
        operacao.quantidade = Decimal(valor_operacao / valor_cota)

        # individualizando os custos de transação e imposto de renda
        operacao.custos_transacao = Decimal(
            operacao.custos_transacao / operacao.quantidade
        )
        operacao.ir_fonte = Decimal(operacao.ir_fonte / operacao.quantidade)

        operacao.save()

        mensagem = 'Cadastrada a {} do {} registrada com sucesso'.format(
            operacao.operacao,
            operacao.ativo_perfil_caixa,
        )
        messages.success(self.request, mensagem)
        return redirect('invest_operacao:operacao_individual')


class OperacaoIndividualEditar(LoginRequiredMixin, UpdateView):
    form_class = FormExtratoOperacaoBolsa
    model = ExtratoOperacao
    template_name = 'registrar_operacao_individual.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['id_perfil_selecionado'] = Funcoes_auxiliares.get_perfil_ativo(
            self.request, **kwargs
        )
        context['nome_parametro'] = 'registrar compra ou venda'

        # Campo formulário
        context['form'].fields[
            'ativo_perfil_caixa'
        ].queryset = AtivoPerfilCaixa.objects.filter(
            subclasse__caixa__perfil=context['id_perfil_selecionado']
        )

        return context

    def form_valid(self, form, **kwargs):
        operacao = form.save(commit=False)
        operacao.save()
        messages.success(
            self.request,
            'Operação de {} atualizada com sucesso'.format(
                form.cleaned_data['operacao']
            ),
        )
        return redirect('invest_operacao:operacao_individual')


class RegistraNotaCorretagem(LoginRequiredMixin, FormView):
    form_class = FormOperacaoNotaCorretagem
    template_name = 'registrar_nota_corretagem.html'
    nota = registrar_nota_corretagem()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['id_perfil_selecionado'] = Funcoes_auxiliares.get_perfil_ativo(
            self.request, **kwargs
        )
        context['titulo_pagina'] = 'Registrar nota de corretagem'
        context['nome_botao_form'] = 'Incluir ativo'

        context['form'].fields['ativoPerfilCaixa'].choices = (
            AtivoPerfilCaixa.objects.annotate(
                ativo_com_ticket=Concat(
                    'ativo__ticket', Value(' : '), 'ativo__nome'
                )
            )
            .filter(
                subclasse__caixa__perfil__pk=context['id_perfil_selecionado']
            )
            .values_list('pk', 'ativo_com_ticket')
            .order_by('ativo_com_ticket')
        )

        if self.request.GET.get('atualizar_nota'):
            self.atualiza_nota_corretagem()

        if self.request.GET.get('incluirAtivo'):
            self.incluir_ativo_nota()

        if self.kwargs.get('id_linha') is not None:
            self.nota.id_linha_selecionada = int(self.kwargs.get('id_linha'))
            context = self.carrega_dados_linha(context)

        if self.request.GET.get('salvar'):
            retorno = self.nota.salvar_operacoes_nota()
            messages.success(self.request, retorno)

        if self.request.GET.get('novaNota'):
            self.nota.nova_nota_corretagem()

        context['data'] = self.nota._data
        context['total_custos'] = str(self.nota._total_custos)
        context['ir_fonte'] = str(self.nota._ir_fonte)

        context['table'] = tabelaNotaCorretagem(
            self.nota.get_dict_nota_corretagem()
        )

        return context

    def incluir_ativo_nota(self):
        """
        Função para incluir ou atualizar um ativo na nota de corretagem

        Returns:
            None
        """

        ativo_perfil_caixa_id = Funcoes_auxiliares.converte_numero_str(
            self.request.GET.get('ativoPerfilCaixa')
        )
        operacao = self.request.GET.get('operacao')
        quantidade = Funcoes_auxiliares.converte_numero_str(
            self.request.GET.get('quantidade')
        )
        valor_unitario = Funcoes_auxiliares.converte_numero_str(
            self.request.GET.get('valor_unitario')
        )

        if self.nota.id_linha_selecionada != -1:
            self.nota.alterar_ativo_nota(
                ativo_perfil_caixa_id, operacao, quantidade, valor_unitario
            )
            self.nota.id_linha_selecionada = -1
        else:
            self.nota.incluir_ativo_nota(
                ativo_perfil_caixa_id, operacao, quantidade, valor_unitario
            )

invest_operacao/templates/operacao_historico_ativo.html
{% extends 'modelo_investimentos.html' %}
{% load crispy_forms_tags %}

{% block titulo_pagina %}
    {{ titulo_pagina }}
{% endblock %}

{% block conteudo_investimentos %}

<div class="flex flex-wrap justify-center space-x-2">

    <div class= "grid justify-center">
        <div class=" grid gap-x-4 gap-y-0 bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"> 
            <form method="get">
                {% csrf_token %}
                {{ filter.form|crispy }}
                <button class="bg-amber-900 w-full rounded-md text-white text-lg" type="submit">Filtrar</button>
            </form>
        </div>
    </div>

    <div class= "grid justify-center">
        <div class=" grid grid-cols-1 grid-rows-2 gap-x-4 gap-y-0 bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"> 
            <p class="col-start-2 row-start-1 text-gray-500" >
                Ativo listado em bolsa
            </p>

            <a href="{% url 'invest_operacao:operacao_individual_bolsa_nova' %}" 
            class=" col-start-2 row-start-2 border rounded-md py-1 px-4 bg-amber-900 text-white inline-block rounded"> 
                Cadastrar operação
            </a>
        </div>
    </div>

    <div class= "grid justify-center">
        <div class=" grid grid-cols-1 grid-rows-2 gap-x-4 gap-y-0 bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"> 
            <p class="col-start-2 row-start-1 text-gray-500" >
                Fundos e ativos não listados
            </p>

            <a href="{% url 'invest_operacao:operacao_individual_fundo_nova' %}" 
            class=" col-start-2 row-start-2 border rounded-md py-1 px-4 bg-amber-900 text-white inline-block rounded"> 
                Cadastrar operação
            </a>
        </div>
    </div>

</div>




{% load django_tables2 %}
{% render_table table %}

{% endblock %}

invest_operacao/templates/operacao_inicio.html
{% extends 'modelo_investimentos.html' %}

{% block titulo_pagina %}
    Registrar operações de compra e venda
{% endblock %}

{% block conteudo_investimentos %}

<h2 class="font-semibold text-xl mt-1"> Cadastrar operações </h2>
<p>Registro das operações de compra e venda de ativos</p>
<br>

<div class="flex flex-wrap justify-between space-x-2">

    <div class="max-w-xs rounded-lg bg-white shadow-lg">
      <div class="p-6">
        <h5
          class="mb-2 text-xl font-medium leading-tight text-neutral-800">
          Ativo individual
        </h5>
        <p class="mb-4 text-base text-neutral-600">
          Registrar operação de compra ou venda de um único ativo
        </p>
        <a href="{% url 'invest_operacao:operacao_individual' %}"> 
            <button
            type="button"
            class="inline-block rounded bg-neutral-700 px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]"
            data-te-ripple-init
            data-te-ripple-color="light">
            Registrar
            </button>
        </a>
      </div>
    </div>

    <div class="max-w-xs rounded-lg bg-white shadow-lg">
      <div class="p-6">
        <h5
          class="mb-2 text-xl font-medium leading-tight text-neutral-800">
          Nota corretagem
        </h5>
        <p class="mb-4 text-base text-neutral-600">
          Registrar operação de compra ou venda de um único ativo
        </p>
        <a href="{% url 'invest_operacao:nota_corretagem' %}"> 
            <button
            type="button"
            class="inline-block rounded bg-neutral-700 px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]"
            data-te-ripple-init
            data-te-ripple-color="light">
            Registrar
            </button>
        </a>
      </div>
    </div>

</div>


<h2 class="font-semibold text-xl mt-1"> Movimentações recentes </h2>
<br>




{% load django_tables2 %}
{% render_table table %}

{% endblock %}

invest_operacao/templates/registrar_nota_corretagem.html
{% extends 'modelo_investimentos.html' %}
{% load crispy_forms_tags %}

{% block titulo_pagina %}
    {{ titulo_pagina }}
{% endblock %}

{% block conteudo_investimentos %}

<div class= "grid justify-center">
    <form method="get" action="{% url 'invest_operacao:nota_corretagem' %}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        <div class="form-group grid grid-cols-4 grid-rows-3 gap-x-4 gap-y-0"> 
            <label for="data" class="col-start-1 row-start-1 form-label text-gray-500">Data operação</label>
            <input type="date" name="data" 
                                value="{{ data|date:'Y-m-d' }}"  
                                placeholder="data da nota" 
                                class= "col-start-1 row-start-2 form-control
                                        rounded-md border-2 border-gray-100 border-solid 
                                        text-black" />
            <label for="total_custos" class="col-start-2 row-start-1 form-label text-gray-500">Total custos </label>
            <input type="number" name="total_custos" 
                                value="{{ total_custos }}"  
                                step = "0.01"
                                placeholder="ex: 0,0" 
                                class= "col-start-2 row-start-2 form-control
                                        rounded-md border-2 border-gray-100 border-solid 
                                        text-black" />
            <label for="ir_fonte" class="col-start-3 row-start-1 form-label text-gray-500">IR Fonte (R$)</label>
            <input type="number" name="ir_fonte" 
                                value="{{ ir_fonte }}"  
                                step = "0.01"
                                placeholder="ex: 0,0" 
                                class= "col-start-3 row-start-2 form-control
                                        rounded-md border-2 border-gray-100 border-solid 
                                        text-black" />          
            <button type="submit" class="col-start-4 row-start-2 form-check 
                                        bg-amber-900 w-full mx-4 rounded-md
                                        text-white text-lg" 
                                  value="Click" 
                                  name="atualizar_nota">
                Atualizar
            </button>
            <button type="submit" class="col-start-4 row-start-4 form-check 
            bg-amber-900 w-full mx-4 rounded-md
            text-white text-lg" 
                                  value="Click" 
                                  name="salvar">
                Salvar nota
            </button>

        </div>
    </form>
</div>

<div class= "grid justify-center">
    {% csrf_token %}
    <form method="get" action="{% url 'invest_operacao:nota_corretagem' %}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        <div class="form-group grid grid-cols-5 grid-rows-1 gap-x-4 gap-y-0">
            <div class="col-start-1 row-start-1">
                {{ form.ativoPerfilCaixa|as_crispy_field }}
            </div>
            <div class="col-start-2 row-start-1">
                {{ form.operacao|as_crispy_field }}
            </div>
            <div class="col-start-3 row-start-1">
                {{ form.quantidade|as_crispy_field }}
            </div>
            <div class="col-start-4 row-start-1">
                {{ form.valor_unitario|as_crispy_field }}
            </div>
            <button type="submit" class="col-start-5 row-start-1 form-check 
                                        bg-amber-900 w-full mx-4 rounded-md
                                        text-white text-lg" 
                                  value="Click" 
                                  name="incluirAtivo">
                {{ nome_botao_form }}
            </button>

        </div>
    </form>    




</div>


{% load django_tables2 %}
{% render_table table %}

 


<div class= "grid justify-center">
  <form method="get" action="{% url 'invest_operacao:nota_corretagem' %}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
      <div class="form-group grid grid-cols-1 grid-rows-1 gap-x-0 gap-y-0"> 
        <button type="submit" class="col-start-4 row-start-1 form-check 
        bg-amber-900 w-full mx-4 rounded-md
        text-white text-lg" 
                value="Click" 
                name="novaNota">
                    Cadastrar nova nota
        </button> 
      </div>
  </form>
</div>

{% endblock %}

invest_operacao/templates/registrar_operacao_individual.html
{% extends 'modelo_investimentos.html' %}
{% load crispy_forms_tags %}

{% block titulo_pagina %}
    {% if form.instance.pk %}
            Atualizar {{ nome_parametro }}
    {% else %}
            Cadastrar {{ nome_parametro }}
    {% endif %}
{% endblock %}

{% block conteudo_investimentos %}

<div class= "grid justify-center">
    <form action="" method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            {{form|crispy}}
        </fieldset>
        <button class="bg-amber-900 w-full rounded-md text-white text-lg" type="submit">Salvar</button>
    </form>
</div>

{% endblock %}